FROM alpine:latest
RUN apk add curl gcompat && mkdir -p /opt/wordcloud 
RUN curl -u downloader:123 -X GET "http://nexus:8081/repository/word-cloud-build/$git_branch/word-cloud-generator/1.$BUILD_NUMBER/word-cloud-generator-1.$BUILD_NUMBER.gz" -o /opt/wordcloud/word-cloud-generator.gz
RUN gunzip -f /opt/wordcloud/word-cloud-generator.gz && chmod +x /opt/wordcloud/word-cloud-generator
WORKDIR /opt/wordcloud
EXPOSE 8888
CMD /word-cloud-generator
